parameters:
#    sonata_admin.example.class: Sonata\AdminBundle\Example

services:
#    sonata_admin.example:
#        class: %sonata_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
